LISTE:
    - apache2
    - php
    - libapache2-mod-php
    - php-imap
    - php-ldap
    - php-curl
    - php-xmlrpc
    - php-gd
    - php-mysql
    - php-cas
    - mariadb-server
    - apcupsd
    - php-apcu
    - php-intl
    - php-mbstring



CONFIG :
    'user': 'root'
    'password': '19022012'
    'host': 'localhost'
    'unix_socket' : '/var/run/mysqld/mysqld.sock'

URL: https://github.com/glpi-project/glpi/releases/download/9.5.5/glpi-9.5.5.tgz

PATH: /var/www/html/







